# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{named-routes}
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Takita"]
  s.date = %q{2010-12-29}
  s.email = %q{brian.takita@gmail.com}
  s.extra_rdoc_files = [
    "CHANGES",
    "README.md"
  ]
  s.files = [
    "CHANGES",
    "Gemfile",
    "Gemfile.lock",
    "MIT.LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/named-routes.rb",
    "lib/named-routes/routes.rb",
    "lib/named-routes/schemed_uri.rb",
    "spec/named-routes/routes_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/btakita/named-routes}
  s.rdoc_options = ["--main", "README.md", "--inline-source", "--line-numbers"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple and generic named routes api. It works really well with Sinatra.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<extlib>, ["= 0.9.15"])
      s.add_runtime_dependency(%q<extlib>, [">= 0.9.15"])
    else
      s.add_dependency(%q<extlib>, ["= 0.9.15"])
      s.add_dependency(%q<extlib>, [">= 0.9.15"])
    end
  else
    s.add_dependency(%q<extlib>, ["= 0.9.15"])
    s.add_dependency(%q<extlib>, [">= 0.9.15"])
  end
end

